name: Check Dependencies

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check jq and gh
        run: |
          echo "jq:"
          command -v jq
          jq --version

          echo ""
          echo "gh:"
          command -v gh
          gh --version
